# Generated by Django 2.0.7 on 2018-07-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('price_tall', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price_grande', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price_venti', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
