# Generated by Django 2.0.7 on 2018-07-30 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0002_auto_20180730_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='volume',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 30, 19, 15, 22, 299864)),
        ),
    ]
